apiVersion: batch/v1
kind: Job
metadata:
  name: churn-train
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: churn-volume
          persistentVolumeClaim:
            claimName: churn-storage
      containers:
        - name: train
          image: churn-api:v1
          command: ["python", "src/train.py"]
          volumeMounts:
            - name: churn-volume
              mountPath: /app/models
              subPath: models
            - name: churn-volume
              mountPath: /app/registry
              subPath: registry